@startuml
skinparam linetype polyline


Interface Visitor{
}
Interface VisitableElement{
}

class Partition {
}

' Tracks
class Note {
}

' TemporalGrid
class Composition {
}
class Section {
}
class Bar {
}
class Beat {
}
class Tick {
}



' Enum Declaration
enum DrumsElements {

}

' All attributes

Partition "1" *--> "1" Composition : composition


' Grid
Composition "1" --> "*" Section : sections
Section "1" --> "*" Bar : bars
Bar "1" --> "*" Beat : beats
Beat "1" --> "*" Tick : ticks
Beat "*" --> "*" Note : musicNote
Tick "*" --> "*" Note : musicNote

@enduml